package CodeGeneration;

import AST.JinjaCss.HtmlElement;
import AST.JinjaCss.HtmlElements.*;
import AST.JinjaCss.JinjaExpression;
import AST.JinjaCss.JinjaExpressions.*;
import AST.JinjaCss.Program;
import AST.JinjaCss.Statement;
import AST.JinjaCss.Statements.*;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Translates a Jinja template into a Python function that builds the same page.
 *
 * The compile-time generator ({@link JinjaCodeGenerator}) can only render the page
 * once, against whatever data the program happened to hold before it ran. This
 * generator instead turns {% for %} into a Python for, {% if %} into a Python if,
 * and {{ x }} into a lookup, so the page is rebuilt from live data every time the
 * Flask app renders it - with no Jinja left anywhere in the output.
 */
public class PythonTemplateGenerator {

    /**
     * Jinja filters that map onto a Python expression. %s is the filtered value.
     */
    private static final Map<String, String> FILTERS = new LinkedHashMap<>();

    static {
        FILTERS.put("upper", "_str(%s).upper()");
        FILTERS.put("lower", "_str(%s).lower()");
        FILTERS.put("title", "_str(%s).title()");
        FILTERS.put("capitalize", "_str(%s).capitalize()");
        FILTERS.put("trim", "_str(%s).strip()");
        FILTERS.put("length", "len(%s or \"\")");
        FILTERS.put("count", "len(%s or \"\")");
        FILTERS.put("int", "int(%s or 0)");
        FILTERS.put("float", "float(%s or 0)");
        FILTERS.put("round", "round(float(%s or 0))");
        FILTERS.put("abs", "abs(%s or 0)");
    }

    private final RouteTable routes;
    private final List<String> warnings;

    private final StringBuilder out = new StringBuilder();

    /**
     * Markup that has been produced but not yet written out as a call, so that a
     * run of static HTML becomes one block of appends instead of one per node.
     */
    private final StringBuilder pending = new StringBuilder();

    /**
     * Indentation of the Python being emitted, in 4-space steps.
     */
    private int pythonIndent = 1;

    /**
     * Indentation of the HTML being produced, in 2-space steps.
     */
    private int htmlIndent = 0;

    private boolean atStart = true;

    public PythonTemplateGenerator(RouteTable routes, List<String> warnings) {
        this.routes = routes;
        this.warnings = warnings;
    }

    /**
     * The helpers every generated render function relies on.
     */
    public static String prelude() {
        return """
                \"""Generated by the PyFlask compiler - do not edit.

                One function per template. Each one builds the page as plain HTML,
                rewrites templates/<name>.html with it, and hands the markup back to
                the route. Jinja is never involved.
                \"""

                import html as _html
                import os as _os

                _BASE_DIR = _os.path.dirname(_os.path.abspath(__file__))
                _TEMPLATE_DIR = _os.path.join(_BASE_DIR, "templates")


                def _get(value, name):
                    \"""Attribute lookup that works for dicts and objects alike.\"""
                    if value is None:
                        return ""
                    if isinstance(value, dict):
                        return value.get(name, "")
                    return getattr(value, name, "")


                def _str(value):
                    if value is None:
                        return ""
                    return str(value)


                def _esc(value):
                    return _html.escape(_str(value), quote=True)


                def _add(left, right):
                    if isinstance(left, str) or isinstance(right, str):
                        return _str(left) + _str(right)
                    return left + right


                def _write(name, markup):
                    _os.makedirs(_TEMPLATE_DIR, exist_ok=True)
                    path = _os.path.join(_TEMPLATE_DIR, name)
                    with open(path, "w", encoding="utf-8") as target:
                        target.write(markup)
                """;
    }

    /**
     * Builds the render function for one template.
     *
     * @param templateName file name the function should rewrite, e.g. "list.html"
     * @param functionName name of the generated function, e.g. "render_list"
     * @param parameters   context names the template is rendered with
     */
    public String generate(
            String templateName,
            String functionName,
            List<String> parameters,
            Program program) {

        emitLine("def " + functionName + "(" + signature(parameters) + "):", 0);

        emitLine("_out = []");

        visitStatements(program.getStatements());

        flush();

        emitLine("markup = \"\".join(_out)");
        emitLine("_write(" + pyString(templateName) + ", markup)");
        emitLine("return markup");

        return out.toString();
    }

    private String signature(List<String> parameters) {
        StringBuilder sb = new StringBuilder();

        for (int i = 0; i < parameters.size(); i++) {

            sb.append(parameters.get(i)).append("=None");

            if (i < parameters.size() - 1) {
                sb.append(", ");
            }
        }

        return sb.toString();
    }

    /* ===================== statements ===================== */

    /**
     * Emits a list of statements, keeping neighbouring text and {{ ... }} on the
     * same line. "${{ product.price }}" has to stay "$99.5", not gain a line break
     * between the two halves.
     */
    private void visitStatements(List<Statement> statements) {

        int index = 0;

        while (index < statements.size()) {

            if (!isInlineContent(statements.get(index))) {
                visitStatement(statements.get(index));
                index++;
                continue;
            }

            int end = index;

            while (end < statements.size() && isInlineContent(statements.get(end))) {
                end++;
            }

            visitInlineRun(statements.subList(index, end));

            index = end;
        }
    }

    private boolean isInlineContent(Statement stmt) {
        return stmt instanceof TextStatement
                || stmt instanceof JinjaVariableStatement;
    }

    /**
     * Puts one run of text and expressions on a line of its own, trimming only the
     * source indentation at either end of the run.
     */
    private void visitInlineRun(List<Statement> run) {

        StringBuilder text = new StringBuilder();
        boolean hasExpression = false;

        for (Statement stmt : run) {
            if (stmt instanceof TextStatement node) {
                text.append(node.text);
            } else {
                hasExpression = true;
            }
        }

        // nothing but the template's own indentation
        if (!hasExpression && text.toString().isBlank()) {
            return;
        }

        newline();

        for (int i = 0; i < run.size(); i++) {

            Statement stmt = run.get(i);

            if (stmt instanceof JinjaVariableStatement node) {
                expression(node.expression);
                continue;
            }

            String piece = ((TextStatement) stmt).text;

            if (i == 0) {
                piece = piece.stripLeading();
            }

            if (i == run.size() - 1) {
                piece = piece.stripTrailing();
            }

            if (!piece.isEmpty()) {
                markup(piece);
            }
        }
    }

    private void visitStatement(Statement stmt) {
        if (stmt instanceof HtmlElement node) {
            visitHtmlElement(node);
        } else if (stmt instanceof TextStatement node) {
            visitTextStatement(node);
        } else if (stmt instanceof JinjaVariableStatement node) {
            visitJinjaVariable(node);
        } else if (stmt instanceof JinjaIfStatement node) {
            visitJinjaIf(node);
        } else if (stmt instanceof JinjaForStatement node) {
            visitJinjaFor(node);
        }
    }

    private void visitHtmlElement(HtmlElement node) {
        if (node instanceof NormalHtmlElement n) {
            visitNormalHtmlElement(n);
        } else if (node instanceof SelfClosingHtmlElement n) {
            visitSelfClosingHtmlElement(n);
        } else if (node instanceof StyleElement n) {
            visitStyleElement(n);
        } else if (node instanceof ScriptElement n) {
            visitScriptElement(n);
        }
    }

    private void visitNormalHtmlElement(NormalHtmlElement node) {
        newline();

        markup("<" + node.tagName);
        visitAttributes(node.attributes);
        markup(">");

        if (node.content != null && !node.content.isEmpty()) {

            if (isInline(node)) {

                for (Statement child : node.content) {
                    visitInline(child);
                }

            } else {

                htmlIndent++;

                visitStatements(node.content);

                htmlIndent--;

                newline();
            }
        }

        markup("</" + node.tagName + ">");
    }

    private void visitSelfClosingHtmlElement(SelfClosingHtmlElement node) {
        newline();

        markup("<" + node.tagName);
        visitAttributes(node.attributes);
        markup(" />");
    }

    private void visitStyleElement(StyleElement node) {
        newline();

        markup("<style>\n");
        markup(CssSerializer.serialize(node));
        markup(indentation() + "</style>");
    }

    private void visitScriptElement(ScriptElement node) {
        newline();

        markup("<script>" + node.scriptBody + "</script>");
    }

    private void visitTextStatement(TextStatement node) {
        String text = node.text.trim();

        if (text.isEmpty()) {
            return;
        }

        newline();
        markup(text);
    }

    private void visitJinjaVariable(JinjaVariableStatement node) {
        newline();
        expression(node.expression);
    }

    private void visitJinjaFor(JinjaForStatement node) {
        flush();

        emitLine("for " + node.variable + " in (" + compile(node.iterable) + " or []):");

        pythonIndent++;

        emitBody(node.body);

        pythonIndent--;
    }

    private void visitJinjaIf(JinjaIfStatement node) {
        flush();

        emitLine("if " + compile(node.condition) + ":");

        pythonIndent++;
        emitBody(node.thenBody);
        pythonIndent--;

        if (node.elifStatements != null) {
            for (JinjaElifStatement elif : node.elifStatements) {

                emitLine("elif " + compile(elif.condition) + ":");

                pythonIndent++;
                emitBody(elif.body);
                pythonIndent--;
            }
        }

        if (node.elseStatement != null) {

            emitLine("else:");

            pythonIndent++;
            emitBody(node.elseStatement.body);
            pythonIndent--;
        }
    }

    /**
     * Emits a branch or loop body, guaranteeing the block is never empty so the
     * generated Python always parses.
     */
    private void emitBody(List<Statement> body) {
        int before = out.length();

        if (body != null) {
            visitStatements(body);
        }

        flush();

        if (out.length() == before) {
            emitLine("pass");
        }
    }

    /* ===================== inline content ===================== */

    /**
     * True when an element holds nothing but text, so it can stay on one line.
     */
    private boolean isInline(NormalHtmlElement node) {
        for (Statement child : node.content) {
            if (!(child instanceof TextStatement)
                    && !(child instanceof JinjaVariableStatement)) {
                return false;
            }
        }
        return true;
    }

    private void visitInline(Statement stmt) {
        if (stmt instanceof TextStatement node) {
            markup(node.text);
        } else if (stmt instanceof JinjaVariableStatement node) {
            expression(node.expression);
        }
    }

    private void visitAttributes(List<HtmlAttribute> attributes) {
        if (attributes == null) {
            return;
        }

        for (HtmlAttribute attribute : attributes) {

            markup(" " + attribute.name);

            if (attribute.value == null) {
                continue;
            }

            markup("=\"");

            for (Object part : attribute.parts) {
                if (part instanceof JinjaExpression expr) {
                    expression(expr);
                } else {
                    markup(String.valueOf(part));
                }
            }

            markup("\"");
        }
    }

    /* ===================== expressions ===================== */

    /**
     * Compiles a Jinja expression to the Python source that evaluates it.
     */
    private String compile(JinjaExpression expr) {

        if (expr instanceof JinjaIdentifier node) {
            return compileIdentifier(node);
        }

        if (expr instanceof JinjaString node) {
            return pyString(node.value);
        }

        if (expr instanceof JinjaNumber node) {
            return String.valueOf(node.value);
        }

        if (expr instanceof JinjaBooleanExpression node) {
            return node.value ? "True" : "False";
        }

        if (expr instanceof JinjaParenthesesExpression node) {
            return "(" + compile(node.expression) + ")";
        }

        if (expr instanceof JinjaBinaryExpression node) {
            return compileBinary(node);
        }

        if (expr instanceof JinjaFilterExpression node) {
            return compileFilter(node);
        }

        if (expr instanceof JinjaCallExpression node) {
            return compileCall(node);
        }

        warn("Unsupported expression " + expr + " on line " + expr.line);

        return "\"\"";
    }

    private String compileIdentifier(JinjaIdentifier node) {
        String result = node.parts.get(0);

        for (int i = 1; i < node.parts.size(); i++) {
            result = "_get(" + result + ", " + pyString(node.parts.get(i)) + ")";
        }

        return result;
    }

    private String compileBinary(JinjaBinaryExpression node) {
        String left = compile(node.left);
        String right = compile(node.right);

        // Jinja's + doubles as string concatenation, so the choice is made at runtime
        if (node.op.equals("+")) {
            return "_add(" + left + ", " + right + ")";
        }

        return "(" + left + " " + node.op + " " + right + ")";
    }

    private String compileFilter(JinjaFilterExpression node) {
        String value = compile(node.expression);

        String template = FILTERS.get(node.filterName);

        if (template == null) {
            warn("Unknown filter '" + node.filterName + "' on line " + node.line
                    + "; the value is used unfiltered");
            return value;
        }

        return template.replace("%s", value);
    }

    /**
     * url_for is the only call a template can make, and it is resolved here from
     * the @app.route rules rather than being left for Flask to answer.
     */
    private String compileCall(JinjaCallExpression node) {

        if (!node.name.equals("url_for")) {
            warn("Unknown function '" + node.name + "' on line " + node.line);
            return "\"\"";
        }

        if (node.positional.isEmpty()
                || !(node.positional.get(0) instanceof JinjaString endpoint)) {
            warn("url_for on line " + node.line + " needs a literal endpoint name");
            return "\"\"";
        }

        if (endpoint.value.equals("static")) {
            return compileStaticUrl(node);
        }

        RouteTable.Route route = routes.get(endpoint.value);

        if (route == null) {
            warn("url_for('" + endpoint.value + "') on line " + node.line
                    + " does not match any @app.route");
            return "\"\"";
        }

        List<String> pieces = new ArrayList<>();
        List<String> used = new ArrayList<>();

        for (int i = 0; i < route.literals.size(); i++) {

            String literal = route.literals.get(i);

            if (!literal.isEmpty()) {
                pieces.add(pyString(literal));
            }

            if (i < route.parameters.size()) {

                String parameter = route.parameters.get(i);
                JinjaExpression argument = node.keyword.get(parameter);

                if (argument == null) {
                    warn("url_for('" + endpoint.value + "') on line " + node.line
                            + " is missing the '" + parameter + "' argument");
                    continue;
                }

                pieces.add("_str(" + compile(argument) + ")");
                used.add(parameter);
            }
        }

        pieces.addAll(queryString(node, used));

        return join(pieces);
    }

    private String compileStaticUrl(JinjaCallExpression node) {

        JinjaExpression filename = node.keyword.get("filename");

        if (filename == null) {
            warn("url_for('static') on line " + node.line + " has no filename");
            return "\"\"";
        }

        return join(List.of(
                pyString("/static/"),
                "_str(" + compile(filename) + ")"));
    }

    /**
     * Keyword arguments that no converter in the rule consumed become a query
     * string, the same way Flask's url_for treats them.
     */
    private List<String> queryString(JinjaCallExpression node, List<String> used) {

        List<String> pieces = new ArrayList<>();
        boolean first = true;

        for (Map.Entry<String, JinjaExpression> entry : node.keyword.entrySet()) {

            if (used.contains(entry.getKey())) {
                continue;
            }

            pieces.add(pyString((first ? "?" : "&") + entry.getKey() + "="));
            pieces.add("_str(" + compile(entry.getValue()) + ")");

            first = false;
        }

        return pieces;
    }

    private String join(List<String> pieces) {

        if (pieces.isEmpty()) {
            return "\"\"";
        }

        if (pieces.size() == 1) {
            return pieces.get(0);
        }

        return "(" + String.join(" + ", pieces) + ")";
    }

    /* ===================== output ===================== */

    /**
     * Queues static markup.
     */
    private void markup(String text) {
        pending.append(text);
        atStart = false;
    }

    /**
     * Queues a value that is only known when the page is rendered.
     */
    private void expression(JinjaExpression expr) {
        flush();

        emitLine("_out.append(_esc(" + compile(expr) + "))");

        atStart = false;
    }

    private void newline() {
        if (atStart) {
            return;
        }

        pending.append("\n").append(indentation());
    }

    private String indentation() {
        return "  ".repeat(htmlIndent);
    }

    /**
     * Turns queued markup into appends, one per line of HTML so the generated
     * module stays readable.
     */
    private void flush() {
        if (pending.isEmpty()) {
            return;
        }

        String text = pending.toString();
        pending.setLength(0);

        int start = 0;

        while (start < text.length()) {

            int newline = text.indexOf('\n', start);

            String line = newline < 0
                    ? text.substring(start)
                    : text.substring(start, newline + 1);

            emitLine("_out.append(" + pyString(line) + ")");

            start = newline < 0 ? text.length() : newline + 1;
        }
    }

    private void emitLine(String text) {
        emitLine(text, pythonIndent);
    }

    private void emitLine(String text, int indent) {
        out.append("    ".repeat(indent))
                .append(text)
                .append("\n");
    }

    private void warn(String message) {
        warnings.add(message);
    }

    /**
     * Renders text as a Python string literal.
     */
    public static String pyString(String text) {
        StringBuilder sb = new StringBuilder("\"");

        for (char c : text.toCharArray()) {
            switch (c) {
                case '\\' -> sb.append("\\\\");
                case '"' -> sb.append("\\\"");
                case '\n' -> sb.append("\\n");
                case '\r' -> sb.append("\\r");
                case '\t' -> sb.append("\\t");
                default -> sb.append(c);
            }
        }

        return sb.append("\"").toString();
    }
}
